services:
  synapse:
    container_name: synapse-2
    build: .
    restart: unless-stopped
    ports:
      - "8088:8088"
    volumes:
      # This matches your 'synapse-data' volume from your docker run command
      - ./data:/data
      - ./homeserver.yaml:/data/homeserver.yaml:ro
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    depends_on:
      - db


  db:
    image: postgres:16-alpine
    container_name: synapse-2_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=synapse
      # Required for Synapse to handle encoding correctly
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - synapse-2-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    command: -p 5433

volumes:
  synapse-2-db-data:
