services:
  synapse:
    container_name: synapse
    build: .
    restart: unless-stopped
    ports:
      - "8008:8008"
    volumes:
      # This matches your 'synapse-data' volume from your docker run command
      - synapse-data:/data
      - ./homeserver.yaml:/data/homeserver.yaml:ro
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml


  db:
    image: postgres:16-alpine
    container_name: synapse_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=synapse
      # Required for Synapse to handle encoding correctly
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - synapse-db-data:/var/lib/postgresql/data
      
volumes:
  synapse-data:
    external: true  # This tells Docker to use the volume you already created
  synapse-db-data: